### ISSUE TITLE
Wear OS: Crash on scrolling menu settings

### ISSUE THREAD

**Issue by Andries-Smit** [nightscout/AndroidAPS#1789]
With the latest build 3.0.0.2dev-l On the watch app
- double click on a watch face to open the menu 
- got to Settings 
- Scrolling down the app 
- Result forces the app to close

With an exceptions
- java.lang.IllegalArgumentException: Primary directory AAPS not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
-  java.io.FileNotFoundException: /storage/emulated/0/AAPS/logs/info.nightscout.androidaps/AndroidAPS.log: open failed: ENOENT (No such file or directory)

**The ADB log shows**
2022-05-30 21:36:54.329 27637-27637/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-05-30 21:36:54.497 592-622/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{19492ed u0 info.nightscout.androidaps/.interaction.WatchfaceConfigurationActivity t-1 f}}
2022-05-30 21:36:54.832 1199-32610/? W/MediaProvider: Forgot to handle a top level directory in getContentUriForFile?
2022-05-30 21:36:54.835 1199-32610/? E/MediaProvider: insertFileIfNecessary failed
    java.lang.IllegalArgumentException: Primary directory AAPS not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
        at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:2962)
        at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:2618)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:3365)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3919)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:3630)
        at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:7366)
        at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:7460)
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,565 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [assets/logback.xml] at [assets/logback.xml]
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,582 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,717 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,718 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [file]
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,766 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use zip compression
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,767 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /storage/emulated/0/AAPS/logs/info.nightscout.androidaps/AndroidAPS._%d{yyyy-MM-dd}_%d{HH-mm-ss, aux}_.%i for the active file
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,771 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7a97dbd - The date pattern is 'yyyy-MM-dd' from file name pattern '/storage/emulated/0/AAPS/logs/info.nightscout.androidaps/AndroidAPS._%d{yyyy-MM-dd}_%d{HH-mm-ss, aux}_.%i.zip'.
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,771 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7a97dbd - Roll-over at midnight.
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,776 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7a97dbd - Setting initial period to Mon May 30 21:36:54 GMT+02:00 2022
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,787 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,823 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file] - Active log file name: /storage/emulated/0/AAPS/logs/info.nightscout.androidaps/AndroidAPS.log
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,823 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[file] - File property is set to [/storage/emulated/0/AAPS/logs/info.nightscout.androidaps/AndroidAPS.log]
2022-05-30 21:36:54.868 27637-27637/? I/System.out: 21:36:54,836 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[file] - openFile(/storage/emulated/0/AAPS/logs/info.nightscout.androidaps/AndroidAPS.log,true) failed java.io.FileNotFoundException: /storage/emulated/0/AAPS/logs/info.nightscout.androidaps/AndroidAPS.log: open failed: EPERM (Operation not permitted)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at java.io.FileNotFoundException: /storage/emulated/0/AAPS/logs/info.nightscout.androidaps/AndroidAPS.log: open failed: EPERM (Operation not permitted)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at libcore.io.IoBridge.open(IoBridge.java:492)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(Unknown Source:7)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.FileAppender.openFile(Unknown Source:57)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.FileAppender.start(Unknown Source:58)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(Unknown Source:216)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.joran.action.AppenderAction.end(Unknown Source:11)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Unknown Source:23)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Unknown Source:32)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Unknown Source:11)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(Unknown Source:84)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source:16)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source:34)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source:7)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source:36)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source:7)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source:16)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at org.slf4j.impl.StaticLoggerBinder.getSingleton(Unknown Source:0)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at info.nightscout.shared.logging.AAPSLoggerProduction.debug(AAPSLoggerProduction.kt:22)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at info.nightscout.androidaps.Aaps.onCreate(Aaps.kt:27)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6746)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at android.app.ActivityThread.access$1300(ActivityThread.java:241)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1920)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at android.os.Handler.dispatchMessage(Handler.java:106)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at android.os.Looper.loop(Looper.java:246)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at android.app.ActivityThread.main(ActivityThread.java:7690)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at java.lang.reflect.Method.invoke(Native Method)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
2022-05-30 21:36:54.869 27637-27637/? I/System.out:     at 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
2022-05-30 21:36:54.870 27637-27637/? I/System.out: Caused by: android.system.ErrnoException: open failed: EPERM (Operation not permitted)
2022-05-30 21:36:54.870 27637-27637/? I/System.out:     at 	at libcore.io.Linux.open(Native Method)
2022-05-30 21:36:54.870 27637-27637/? I/System.out:     at 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
2022-05-30 21:36:54.870 27637-27637/? I/System.out:     at 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
2022-05-30 21:36:54.870 27637-27637/? I/System.out:     at 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
2022-05-30 21:36:54.870 27637-27637/? I/System.out:     at 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7576)
2022-05-30 21:36:54.870 27637-27637/? I/System.out:     at 	at libcore.io.IoBridge.open(IoBridge.java:478)
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 	at 	... 33 common frames omitted
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,836 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.android.LogcatAppender]
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,837 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [logcat]
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,840 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [tagEncoder] property
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,850 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,858 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,858 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [file] to Logger[ROOT]
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,859 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [logcat] to Logger[ROOT]
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,859 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
2022-05-30 21:36:54.870 27637-27637/? I/System.out: 21:36:54,860 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@4a84fb2 - Registering current configuration as safe fallback point
2022-05-30 21:36:54.874 27637-27637/? D/WEAR: [main]: [Aaps.onCreate():27]: onCreate

**Comment by MilosKozak** [comment]
this is not related to any crash ... only missing permission on watch. 
i don't think it's necessary to store logs on watch because of it's battery and memory

**Comment by reijoahola-nightscout** [comment]
I tested this with the latest 3.0.0.2-dev-l (a091b6c32) and using TicWatch Pro (year 2018 model). I did not have the same problem, I could easily scroll the settings menu to the bottom in the watchface (AAPS Digital Style).

**Comment by Andries-Smit** [comment]
After uninstalling and installing again, with default settings,  it does not crash. So it could be a non-default setting or an error in the stored settings.

I would agree that logs should not be enabled, by default. maybe it should be a switch users can enable in case they have troubles
