### ISSUE TITLE
3.1.0 White Theme Problems

### ISSUE THREAD

**Issue by m4nnihuber** [nightscout/AndroidAPS#1920]
When using Light Theme on a Pixel 5 App crashes and can't be restarted.
Keeps on crashing and AAPS doesnt open again

**Comment by osodebailar** [comment]
What version before updating?
Try a clean install and reimport your settings.

**Comment by m4nnihuber** [comment]
Came from 3.0.0.1 

clean installation tried but no solution.
app keeps crashing when switching to light theme

**Comment by osodebailar** [comment]
If you install it clean without import settings and than switch to white theme it also crashes ?

**Comment by m4nnihuber** [comment]
yes. same problem

**Comment by osodebailar** [comment]
That’s very strange .
You can send a logfile and maybe write me in messenger for further discussion if you want

**Comment by MilosKozak** [comment]
https://console.firebase.google.com/u/0/project/androidaps-c34f8/crashlytics/app/android:info.nightscout.androidaps/issues/e7837a05364e6f62fcace2ec3536caef?time=last-thirty-days&versions=3.1.0%20(1500);3.0.0.2-dev-o%20(1500)&sessionEventKey=62D70FE100B000017F956356B90FD450_1700624401145498450

**Comment by pimeys** [comment]
Can confirm same behavior on a OnePlus 8 Pro. Already downgraded, so sadly no logfile. Ping me in Discord if I can add something to the issue.

**Comment by lucasvreis** [comment]
Since people on discord were reporting the issue, I ran v3.1with logcat and the first time I changed the theme to white, it gave me this:
```log
--------- beginning of crash
07-19 18:54:43.827 19270 19270 E AndroidRuntime: FATAL EXCEPTION: main
07-19 18:54:43.827 19270 19270 E AndroidRuntime: Process: info.nightscout.androidaps, PID: 19270
07-19 18:54:43.827 19270 19270 E AndroidRuntime: android.view.InflateException: Binary XML file line #68 in info.nightscout.androidaps:layout/overview_fragment: Binary XML file line #68 in info.nightscout.androidaps:layout/overview_fragment: Error inflating class <unknown>
07-19 18:54:43.827 19270 19270 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #68 in info.nightscout.androidaps:layout/overview_fragment: Error inflating class <unknown>
07-19 18:54:43.827 19270 19270 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at info.nightscout.androidaps.databinding.OverviewFragmentBinding.inflate(OverviewFragmentBinding.java:139)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at info.nightscout.androidaps.plugins.general.overview.OverviewFragment.onCreateView(OverviewFragment.kt:148)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8315)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:65)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6301)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2448)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 2: TypedValue{t=0x2/d=0x7f040132 a=11}
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:598)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at androidx.cardview.widget.CardView.<init>(CardView.java:127)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:164)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	at com.google.android.material.card.MaterialCardView.<init>(MaterialCardView.java:160)
07-19 18:54:43.827 19270 19270 E AndroidRuntime: 	... 42 more
07-19 18:54:44.000 19270 19278 I cout.androidap: Background concurrent copying GC freed 310272(18MB) AllocSpace objects, 132(4000KB) LOS objects, 46% free, 27MB/51MB, paused 309us,283us total 142.578ms
07-19 18:54:44.012 19270 19393 D OpenGLRenderer: setSurface called with nullptr
07-19 18:54:44.012 19270 19279 D InputTransport: Input channel destroyed: 'ClientS', fd=190
07-19 18:54:44.013 19270 19393 D OpenGLRenderer: setSurface called with nullptr
07-19 18:54:44.018 19270 19393 D OpenGLRenderer: setSurface called with nullptr
07-19 18:54:44.182 19270 19270 I Process : Sending signal. PID: 19270 SIG: 9
```
Phone is Samsung A32, running Android 12 and One UI 4.1

**Comment by osodebailar** [comment]
@lucasvreis thx for the log . Maybe it will help.

**Comment by osodebailar** [comment]
@MilosKozak : solved with https://github.com/nightscout/AndroidAPS/pull/1926. Maybe you can make a hotfix for 3.1.0
