### ISSUE TITLE
[DEV][NSV3] No connection to NS

### ISSUE THREAD

**Issue by jbr7rr** [nightscout/AndroidAPS#2342]
Build: 6fb8339238-2023.01.12 (dev-g) fullrelease
Logs: [AndroidAPS_2023-01-12-15_JB.zip](https://github.com/nightscout/AndroidAPS/files/10402577/AndroidAPS_2023-01-12-15_JB.zip)

Time of occurrence/interest in logs:  14:45

NSClient V3 will not connect to my nightscout

What I have tried already:
- Database reset
- Enabling/disabling ns upload
- different access tokens (created a new one for testing, with admin role)
- Switching back and forth between NSClientV1 and V3

![Screenshot_20230112-144659](https://user-images.githubusercontent.com/60566713/212094974-5a83e444-b496-461b-a82f-163d0968c335.png)

**Comment by MilosKozak** [comment]
14:23:20.538 [DefaultDispatcher-worker-1] E/CORE: [LoadStatusWorker$doWorkAndLog$2.invokeSuspend():27]: Error: 
retrofit2.HttpException: HTTP 404 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

Are you using NS version 14?
PM me config and master password. I'll test

**Comment by jbr7rr** [comment]
Yes NS 14.2.6, PM sent

**Comment by MilosKozak** [comment]
trailing / in url
