### ISSUE TITLE
Assert.assertTrue(expression) tests do not explain failures

### ISSUE THREAD

**Issue by ryanhaining** [nightscout/AndroidAPS#2745]
`assertTrue` with an expression inside often contains little information in a test failure. For example, this `DateUtilTest`

```
Assertions.assertTrue(DateUtil(context).dateString(1513902750000L).contains("22"))
```

Fails opaquely with

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at info.nightscout.androidaps.utils.DateUtilTest.dateStringTest(DateUtilTest.kt:43)
```

Rewritten to use a [truth](https://truth.dev) matcher, the output is much clearer
```
assertThat(DateUtil(context).dateString(1513902750000L)).contains("22")
```

fails with

```
value of           : dateString(...)
expected to contain: 22
but was            : 12/21/17
	at app//info.nightscout.androidaps.utils.DateUtilTest.dateStringTest(DateUtilTest.kt:44)
```

**Comment by ryanhaining** [comment]
There's a lot of other tests that use `assertTrue` which should be using matchers. Can we keep this open for a bit? I am working my way through them and will tag to this issue.
