### ISSUE TITLE
Failed bolus error message when bolus was delivered

### ISSUE THREAD

**Issue by gh4tf** [nightscout/AndroidAPS#3318]
At 16:54 yesterday, I gave my daughter 2.1u of insulin directly using AAPS and got the "Bolus reported an error" message (please see screenshot), but I know that the bolus was definitely delivered by the Combo pump because it delivers insulin in 0.1u increments and I count the little noises the pump makes with each one.

I have included a screenshot of the treatments showing 2.1u was delivered at 16:54 and the main screen of AAPS showing bolus delivery failed in orange on the graph.

I think this is what happened when I received a "bolus failed" text when sending an SMS command recently. I created issue Failed bolus by SMS was actually delivered #3309 for that.

Using AAPS 3.2.0.2 Build c31617f 2023.12.13, Combo, G6, xDrip and Xiaomi A2 Lite. No longer using Ruffy.

@dv1 

[Log Export.txt](https://github.com/nightscout/AndroidAPS/files/15186441/Log.Export.txt)

![bolus reported an error](https://github.com/nightscout/AndroidAPS/assets/68807070/d9308af6-08d2-4461-9683-76276407fa7a)
![bolus delivery failed](https://github.com/nightscout/AndroidAPS/assets/68807070/8728bdc0-b93d-4413-90cf-a1d7a6d5e2b7)
![2 1u delivered in treatments](https://github.com/nightscout/AndroidAPS/assets/68807070/b17838e2-22db-4e1d-a750-a1daa46d75ce)

**Comment by dv1** [comment]
As I said [here](https://github.com/nightscout/AndroidAPS/issues/3309#issuecomment-2090023154), try newest dev.

**Comment by pontomedon** [comment]
@MilosKozak as mentioned [here](https://github.com/nightscout/AndroidAPS/issues/3309#issuecomment-2587085926), this issue is unfortunately not fixed. It started occurring with the new Combo driver (which otherwise works great!), and is still present on `3.3.1.0`.

Pretty sure #3318 and #3309 are duplicates, but one of them should be re-opened, I think.

**Comment by Der-Schubi** [comment]
Can confirm, I have this problem every few days.

**Comment by dv1** [comment]
@Der-Schubi If you can, do the following:

Open the file `pump/combov2/comboctl/src/commonMain/kotlin/info/nightscout/comboctl/base/PumpIO.kt`.

In lines 1662, 1694, 1728, 1733, 1742, 1774, 1807, 1812 change `VERBOSE` to `DEBUG`, like this:

from:

    logger(LogLevel.VERBOSE) { "Starting background CMD ping heartbeat" }

to:

    logger(LogLevel.DEBUG) { "Starting background CMD ping heartbeat" }

Then, when the issue happens again, immediately post logs here.

**Comment by Der-Schubi** [comment]
> Any news here?

Not yet . Got no errors since. May be a timing issue, resolved by the debug logging?

**Comment by pontomedon** [comment]
Had it like 3 or 4 times, but was never fast enough to connect ADB. My wife's the patient, so I have limited opportunities where she injects while being near my computer. I think I'll set up wireless ADB and just connect whenever she's in the apartment :P

**Comment by Der-Schubi** [comment]
> Had it like 3 or 4 times, but was never fast enough to connect ADB.

You can export the logs without ADB, directly in AAPS. In the menu under maintenance is an option to send logs by email.

**Comment by pontomedon** [comment]
> You can export the logs without ADB, directly in AAPS

damn, didn't know that. will do when it happens the next time!

**Comment by dv1** [comment]
I already posted this in Discord, but for higher visibility, I also mention it here:

I added a `comboctl-dev` branch to my https://github.com/dv1/AndroidAPS fork. If you can, try that out and let me know if this fixes the issue for you. Due to the nature of the issue, reproducing it can be very difficult, hence my request.

**Comment by Der-Schubi** [comment]
I think I captured one of the errors today, but had no time to look into the logs for now. I'll have a look and post the logs tomorrow.

**Comment by Der-Schubi** [comment]
@dv1 This was just insulin, no carbs this time. But would I have entered carbs, they would have been deleted.
Bolus was 6U, delivered were the full 6U, but there was a disconnect after ~3U.
```
16:58:39.035 [DefaultDispatcher-worker-10] D/PUMP: [Pump.setState():3620]: [Pump] Setting Combo driver state:  old: info.nightscout.comboctl.main.Pump$State$ReadyForCommands@4ce59f3  new: ExecutingCommand(description=info.nightscout.comboctl.main.Pump$DeliveringBolusCommandDesc@3b63355)
16:58:39.037 [DefaultDispatcher-worker-10] D/PUMPCOMM: [PumpIO.stopCMDPingHeartbeat():2200]: [PumpIO] Background CMD ping heartbeat stopped
16:58:39.037 [DefaultDispatcher-worker-10] D/PUMPCOMM: [PumpIO.startCMDPingHeartbeat():2194]: [PumpIO] Starting background CMD ping heartbeat
16:58:39.065 [DefaultDispatcher-worker-1] D/WORKER: [LoggingWorker$doWork$2.invokeSuspend():27]: Worker result SUCCESS for class app.aaps.plugins.sync.nsclientV3.workers.DataSyncWorker Data {}
16:58:39.243 [DefaultDispatcher-worker-6] D/PUMP: [ApplicationLayer.parseCMDReadErrorWarningStatusResponsePacket():1894]: [ApplicationLayer] Parsing CMD_READ_ERROR_WARNING_STATUS_RESPONSE packet
16:58:39.244 [DefaultDispatcher-worker-6] D/PUMP: [ApplicationLayer.parseCMDReadErrorWarningStatusResponsePacket():1897]: [ApplicationLayer] Error/warning status: CMDErrorWarningStatus(errorOccurred=false, warningOccurred=false)
16:58:39.244 [DefaultDispatcher-worker-6] D/PUMP: [Pump$deliverBolus$3.invokeSuspend():3590]: [Pump] Checking if there is enough insulin in reservoir; reservoir fill level: 141 IU; bolus amount: 6.0 IU(rounded: 6 IU)
16:58:39.244 [DefaultDispatcher-worker-6] D/PUMP: [Pump$deliverBolus$3.invokeSuspend():3593]: [Pump] Beginning bolus delivery of 6.0 IU
16:58:39.244 [DefaultDispatcher-worker-6] D/PUMPCOMM: [PumpIO.stopCMDPingHeartbeat():2200]: [PumpIO] Background CMD ping heartbeat stopped
16:58:39.245 [DefaultDispatcher-worker-6] D/PUMPCOMM: [PumpIO.startCMDPingHeartbeat():2194]: [PumpIO] Starting background CMD ping heartbeat
16:58:39.774 [DefaultDispatcher-worker-6] D/PUMP: [ApplicationLayer.parseCMDDeliverBolusResponsePacket():1936]: [ApplicationLayer] Parsing CMD_DELIVER_BOLUS_RESPONSE packet
16:58:39.775 [DefaultDispatcher-worker-6] D/PUMP: [ApplicationLayer.parseCMDDeliverBolusResponsePacket():1939]: [ApplicationLayer] Bolus started: true
16:58:39.776 [DefaultDispatcher-worker-6] D/PUMP: [Pump$deliverBolus$3.invokeSuspend():3599]: [Pump] Waiting until bolus delivery is complete
16:58:39.778 [DefaultDispatcher-worker-6] D/PUMPCOMM: [PumpIO.stopCMDPingHeartbeat():2200]: [PumpIO] Background CMD ping heartbeat stopped
16:58:40.241 [DefaultDispatcher-worker-1] D/PUMP: [ApplicationLayer.parseCMDGetBolusStatusResponsePacket():1930]: [ApplicationLayer] Parsing CMD_GET_BOLUS_STATUS_RESPONSE packet
16:58:40.243 [DefaultDispatcher-worker-1] D/PUMP: [ApplicationLayer.parseCMDGetBolusStatusResponsePacket():1933]: [ApplicationLayer] Bolus status: CMDBolusDeliveryStatus(bolusType=STANDARD, deliveryState=DELIVERING, remainingAmount=59)
16:58:40.703 [DefaultDispatcher-worker-2] D/PUMP: [ApplicationLayer.parseCMDGetBolusStatusResponsePacket():1930]: [ApplicationLayer] Parsing CMD_GET_BOLUS_STATUS_RESPONSE packet
16:58:40.705 [DefaultDispatcher-worker-2] D/PUMP: [ApplicationLayer.parseCMDGetBolusStatusResponsePacket():1933]: [ApplicationLayer] Bolus status: CMDBolusDeliveryStatus(bolusType=STANDARD, deliveryState=DELIVERING, remainingAmount=58)
[...]
16:58:52.849 [DefaultDispatcher-worker-10] D/PUMP: [ApplicationLayer.parseCMDGetBolusStatusResponsePacket():1930]: [ApplicationLayer] Parsing CMD_GET_BOLUS_STATUS_RESPONSE packet
16:58:52.851 [DefaultDispatcher-worker-10] D/PUMP: [ApplicationLayer.parseCMDGetBolusStatusResponsePacket():1933]: [ApplicationLayer] Bolus status: CMDBolusDeliveryStatus(bolusType=STANDARD, deliveryState=DELIVERING, remainingAmount=34)
16:58:53.320 [DefaultDispatcher-worker-7] D/PUMP: [ApplicationLayer.parseCMDGetBolusStatusResponsePacket():1930]: [ApplicationLayer] Parsing CMD_GET_BOLUS_STATUS_RESPONSE packet
16:58:53.324 [DefaultDispatcher-worker-7] D/PUMP: [ApplicationLayer.parseCMDGetBolusStatusResponsePacket():1933]: [ApplicationLayer] Bolus status: CMDBolusDeliveryStatus(bolusType=STANDARD, deliveryState=DELIVERING, remainingAmount=33)
16:59:02.755 [DefaultDispatcher-worker-10] D/PUMP: [TransportLayer$IO$startInternal$1.invokeSuspend():1263]: [TransportLayer] Caught Combo exception in receive loop: info.nightscout.comboctl.base.ComboIOException: Could not read data from device with address 00:0e:2f:XX:XX:XX
16:59:02.761 [DefaultDispatcher-worker-10] D/PUMP: [TransportLayer$IO$startInternal$1.invokeSuspend():1266]: [TransportLayer] Combo exception stacktrace: info.nightscout.comboctl.base.ComboIOException: Could not read data from device with address 00:0e:2f:XX:XX:XX
	at info.nightscout.comboctl.android.AndroidBluetoothDevice.blockingReceive(AndroidBluetoothDevice.kt:216)
	at info.nightscout.comboctl.base.BlockingComboIO$receive$2.invokeSuspend(ComboIO.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
Caused by: java.io.IOException: bt socket closed, read return: -1
	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:672)
	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:88)
	at java.io.InputStream.read(InputStream.java:218)
	at info.nightscout.comboctl.android.AndroidBluetoothDevice.blockingReceive(AndroidBluetoothDevice.kt:208)
	... 9 more

16:59:02.772 [DefaultDispatcher-worker-6] E/PUMP: [Pump$deliverBolus$3.invokeSuspend():3614]: [Pump] Silently discarding caught exception while cancelling bolus: info.nightscout.comboctl.base.TransportLayer$PacketReceiverException: Could not read data from device with address 00:0e:2f:XX:XX:XX
16:59:02.774 [DefaultDispatcher-worker-6] D/PUMPCOMM: [PumpIO$switchMode$2.invokeSuspend():2086]: [PumpIO] Switching mode from COMMAND to REMOTE_TERMINAL
16:59:02.774 [DefaultDispatcher-worker-6] D/PUMPCOMM: [PumpIO$switchMode$2$3$1.invokeSuspend():2085]: [PumpIO] Deactivating current service
16:59:02.775 [DefaultDispatcher-worker-6] D/PUMP: [Pump.executeCommand():3641]: [Pump] Pump terminated connection, but will not try to reconnect since this is a non-idempotent command
16:59:02.775 [DefaultDispatcher-worker-6] D/PUMP: [Pump.setState():3620]: [Pump] Setting Combo driver state:  old: ExecutingCommand(description=info.nightscout.comboctl.main.Pump$DeliveringBolusCommandDesc@3b63355)  new: Error ("Command execution error"); throwable: info.nightscout.comboctl.base.TransportLayer$PacketReceiverException: Could not read data from device with address 00:0e:2f:XX:XX:XX
16:59:02.780 [DefaultDispatcher-worker-6] E/PUMP: [TransportLayer$IO.stop():1288]: [TransportLayer] Caught error while sending disconnect packet: info.nightscout.comboctl.base.ComboIOException: Could not write data to device with address 00:0e:2f:XX:XX:XX
16:59:02.781 [DefaultDispatcher-worker-6] D/PUMP: [TransportLayer$IO.stop():1291]: [TransportLayer] Disconnecting device
16:59:02.781 [DefaultDispatcher-worker-10] D/PUMPBTCOMM: [AndroidBluetoothDevice.disconnectImpl():297]: [AndroidBluetoothDevice] Closing input stream
16:59:02.782 [DefaultDispatcher-worker-10] D/PUMPBTCOMM: [AndroidBluetoothDevice.disconnectImpl():303]: [AndroidBluetoothDevice] Closing output stream
16:59:02.783 [DefaultDispatcher-worker-10] D/PUMPBTCOMM: [AndroidBluetoothDevice.disconnectImpl():309]: [AndroidBluetoothDevice] Closing Bluetooth socket
16:59:02.783 [DefaultDispatcher-worker-10] D/PUMPBTCOMM: [AndroidBluetoothDevice.disconnectImpl():315]: [AndroidBluetoothDevice] Device disconnected
16:59:02.783 [DefaultDispatcher-worker-10] I/PUMPBTCOMM: [AndroidBluetoothDevice.disconnect():279]: [AndroidBluetoothDevice] RFCOMM connection with device with address 00:0e:2f:XX:XX:XX terminated
16:59:02.784 [DefaultDispatcher-worker-6] D/PUMP: [TransportLayer$IO.stop():1297]: [TransportLayer] Stopping packet receiver
16:59:02.784 [DefaultDispatcher-worker-6] D/PUMP: [TransportLayer$IO.stop():1303]: [TransportLayer] Transport layer IO stopped
16:59:02.785 [DefaultDispatcher-worker-6] D/PUMPCOMM: [PumpIO.disconnect():2109]: [PumpIO] Pump IO disconnected
16:59:02.785 [DefaultDispatcher-worker-6] D/PUMP: [Pump.setState():3620]: [Pump] Setting Combo driver state:  old: Error ("Command execution error"); throwable: info.nightscout.comboctl.base.TransportLayer$PacketReceiverException: Could not read data from device with address 00:0e:2f:XX:XX:XX  new: info.nightscout.comboctl.main.Pump$State$Disconnected@5a1babc
[...]
17:00:00.154 [DefaultDispatcher-worker-6] E/PUMP: [ComboV2Plugin$deliverTreatment$newBolusJob$1.invokeSuspend():1131]: Exception thrown during bolus delivery: info.nightscout.comboctl.base.TransportLayer$PacketReceiverException: Could not read data from device with address 00:0e:2f:XX:XX:XX
17:00:00.240 [main] D/CORE: [ErrorDialog.onCreateView():59]: Error dialog displayed
17:00:00.308 [DefaultDispatcher-worker-9] D/PUMP: [PumpManager.acquirePump():514]: [PumpManager] Getting Pump instance for pump 00:0e:2f:XX:XX:XX
17:00:00.310 [DefaultDispatcher-worker-7] D/PUMP: [Pump.connect():3608]: [Pump] Attempt no. 1 to establish connection
17:00:00.311 [DefaultDispatcher-worker-7] D/PUMP: [Pump.setState():3620]: [Pump] Setting Combo driver state:  old: info.nightscout.comboctl.main.Pump$State$Disconnected@5a1babc  new: info.nightscout.comboctl.main.Pump$State$Connecting@629fa45
17:00:00.311 [DefaultDispatcher-worker-7] D/PUMPCOMM: [PumpIO.connect():2085]: [PumpIO] Pump IO connecting asynchronously
17:00:00.311 [DefaultDispatcher-worker-7] D/PUMPBTCOMM: [AndroidBluetoothDevice.connect():267]: [AndroidBluetoothDevice] Attempting to get object representing device with address 00:0e:2f:XX:XX:XX
17:00:00.311 [DefaultDispatcher-worker-7] D/PUMPBTCOMM: [AndroidBluetoothDevice.connect$lambda$5():318]: [AndroidBluetoothDevice] First attempt to establish an RFCOMM client connection to the Combo
[...]
17:00:06.069 [DefaultDispatcher-worker-7] D/PUMPBTCOMM: [AndroidBluetoothDevice.connect$lambda$5():321]: [AndroidBluetoothDevice] Previous attempt to establish an RFCOMM client connection to the Combo failed withexception "java.io.IOException: read failed, socket might closed or timeout, read ret: -1"; trying again (this is attempt #2 of 5)
17:00:07.409 [DefaultDispatcher-worker-4] D/WORKER: [LoggingWorker$doWork$2.invokeSuspend():27]: Worker result SUCCESS for class app.aaps.plugins.sync.nsclientV3.workers.DataSyncWorker Data {}
17:00:07.801 [RxCachedThreadScheduler-1323] D/CORE: [PersistenceLayerImpl$insertUserEntries$3.apply():1692]: USER ENTRY: 2/16/25 17:00:07 ERROR_DIALOG_OK Unknown  []
17:00:07.865 [RxCachedThreadScheduler-24] D/AUTOMATION: [AutomationPlugin$onStart$12.accept():195]: Grabbed new BT event: EventBTChange[deviceAddress=00:0E:2F:70:DD:F8,deviceName=SpiritCombo,state=CONNECT]
[...]
17:00:09.160 [DefaultDispatcher-worker-7] I/PUMPBTCOMM: [AndroidBluetoothDevice.connect():273]: [AndroidBluetoothDevice] RFCOMM connection with device with address 00:0e:2f:XX:XX:XX established
17:00:09.165 [DefaultDispatcher-worker-3] D/PUMPCOMM: [PumpIO.connect():2088]: [PumpIO] Sending regular connection request
17:00:09.572 [DefaultDispatcher-worker-7] D/PUMPCOMM: [PumpIO.connect():2100]: [PumpIO] Initiating application layer connection
17:00:09.789 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO$switchMode$2.invokeSuspend():2086]: [PumpIO] Switching mode from null to COMMAND
17:00:09.790 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO$switchMode$2$3$1.invokeSuspend():2091]: [PumpIO] Activating new service
17:00:09.988 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO$switchMode$2$3$1.invokeSuspend():2094]: [PumpIO] Sent CTRL_ACTIVATE packet; waiting for CTRL_ACTIVATE_SERVICE_RESPONSE packet
17:00:10.227 [DefaultDispatcher-worker-4] D/PUMPCOMM: [PumpIO.processReceivedPacket():2170]: [PumpIO] New service was activated; resetting RT sequence number
17:00:10.230 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO$switchMode$2.invokeSuspend():2100]: [PumpIO] Resetting heartbeat
17:00:10.232 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO.startCMDPingHeartbeat():2194]: [PumpIO] Starting background CMD ping heartbeat
17:00:10.233 [DefaultDispatcher-worker-11] I/PUMPCOMM: [PumpIO.connect():2103]: [PumpIO] Pump IO connected
17:00:10.234 [DefaultDispatcher-worker-11] D/PUMP: [Pump.setState():3620]: [Pump] Setting Combo driver state:  old: info.nightscout.comboctl.main.Pump$State$Connecting@629fa45  new: info.nightscout.comboctl.main.Pump$State$CheckingPump@408582c
17:00:10.236 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO.stopCMDPingHeartbeat():2200]: [PumpIO] Background CMD ping heartbeat stopped
17:00:10.236 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO.startCMDPingHeartbeat():2194]: [PumpIO] Starting background CMD ping heartbeat
17:00:10.593 [DefaultDispatcher-worker-11] D/PUMP: [ApplicationLayer.parseCMDReadHistoryBlockResponsePacket():1900]: [ApplicationLayer] Parsing CMD_READ_HISTORY_BLOCK_RESPONSE packet
17:00:10.594 [DefaultDispatcher-worker-11] D/PUMP: [ApplicationLayer.parseCMDReadHistoryBlockResponsePacket():1903]: [ApplicationLayer] Packet contains 2 history event(s)
17:00:10.595 [DefaultDispatcher-worker-11] D/PUMP: [ApplicationLayer.parseCMDReadHistoryBlockResponsePacket():1906]: [ApplicationLayer] History block information:  num remaining events: 2  more events available: false  historyGap: false  number of events: 2
17:00:10.595 [DefaultDispatcher-worker-11] D/PUMP: [ApplicationLayer.parseCMDReadHistoryBlockResponsePacket():1909]: [ApplicationLayer] Event #0:  timestamp 2025-02-16T16:57:47  event type ID 14  detail bytes CRC16 checksum 0x4c2a  event counter 1093167  counter CRC16 checksum 0xb4d6  raw detail data bytes 3c 00 00 00
17:00:10.596 [DefaultDispatcher-worker-11] D/PUMP: [ApplicationLayer.parseCMDReadHistoryBlockResponsePacket():1921]: [ApplicationLayer] Detail info: got history event "automatic standard bolus requested" with amount of 6.0 IU
17:00:10.597 [DefaultDispatcher-worker-11] D/PUMP: [ApplicationLayer.parseCMDReadHistoryBlockResponsePacket():1909]: [ApplicationLayer] Event #1:  timestamp 2025-02-16T16:58:17  event type ID 15  detail bytes CRC16 checksum 0x5963  event counter 1093169  counter CRC16 checksum 0xd935  raw detail data bytes 3c 00 00 00
17:00:10.597 [DefaultDispatcher-worker-11] D/PUMP: [ApplicationLayer.parseCMDReadHistoryBlockResponsePacket():1921]: [ApplicationLayer] Detail info: got history event "automatic standard bolus infused" with amount of 6.0 IU
17:00:10.599 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO.stopCMDPingHeartbeat():2200]: [PumpIO] Background CMD ping heartbeat stopped
17:00:10.599 [DefaultDispatcher-worker-11] D/PUMPCOMM: [PumpIO.startCMDPingHeartbeat():2194]: [PumpIO] Starting background CMD ping heartbeat
[...]
17:00:11.294 [DefaultDispatcher-worker-3] D/PUMPCOMM: [PumpIO$switchMode$2.invokeSuspend():2086]: [PumpIO] Switching mode from COMMAND to REMOTE_TERMINAL
[...]
17:00:14.689 [DefaultDispatcher-worker-3] D/PUMP: [ApplicationLayer.parseCMDReadDateTimeResponsePacket():1882]: [ApplicationLayer] Parsing CMD_READ_DATE_TIME_RESPONSE packet
17:00:14.692 [DefaultDispatcher-worker-3] D/PUMP: [ApplicationLayer.parseCMDReadDateTimeResponsePacket():1885]: [ApplicationLayer] Current pump datetime: 2025-02-16T16:59:22
17:00:14.729 [DefaultDispatcher-worker-3] D/PUMP: [Pump.scanHistoryDeltaForBolusToEmit():3676]: [Pump] Found a last bolus in history delta; details: LastBolus(bolusId=1093169, bolusAmount=60, timestamp=2025-02-16T15:58:17Z); now: 2025-02-16T16:00:14.729059Z; lastBolusInfusionTimestamp: 2025-02-16T15:58:17Z -> bolusTimestamp: 2025-02-16T15:58:17Z
[...]
17:00:15.112 [main] D/CORE: [MaintenancePlugin.sendLogs():76]: zipFile: AndroidAPS_LOG_1739721615016.log.zip
17:00:15.119 [main] D/CORE: [MaintenancePlugin.zipLogs():146]: creating zip AndroidAPS_LOG_1739721615016.log.zip
```

**Comment by Der-Schubi** [comment]
@dv1 See new logs in Discord combo-v2 channel.

**Comment by docx1** [comment]
I can confirm that this error is happening again. I thought that it was battery related, changed battery still the same error occurred.
