### ISSUE TITLE
[2.8.2.3-dev] crashes after start

### ISSUE THREAD

**Issue by swissalpine** [nightscout/AndroidAPS#682]
2021-09-20 19:55:45.531 5718-5987/? E/CORE: [RxCachedThreadScheduler-57]: [FabricPrivacy.logException():83]: Exception: 
    java.lang.IndexOutOfBoundsException: Index: 10, Size: 10
    	at java.util.ArrayList.get(ArrayList.java:437) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.constraints.objectives.ObjectivesPlugin.isAutomationEnabled(ObjectivesPlugin.kt:186) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.configBuilder.ConstraintChecker.isAutomationEnabled(ConstraintChecker.kt:218) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.configBuilder.ConstraintChecker.isAutomationEnabled(ConstraintChecker.kt:61) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.general.automation.AutomationPlugin.processActions(AutomationPlugin.kt:191) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.general.automation.AutomationPlugin.onStart$lambda-8(AutomationPlugin.kt:133) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.general.automation.AutomationPlugin.$r8$lambda$Xju3w9kB0-q6HBA1ac04hcL4uMY(Unknown Source:0) ~[na:0.0]
    	at info.nightscout.androidaps.plugins.general.automation.AutomationPlugin$$ExternalSyntheticLambda0.accept(Unknown Source:4) ~[na:0.0]
    	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63) ~[na:0.0]
    	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201) ~[na:0.0]
    	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255) ~[na:0.0]
    	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) ~[na:0.0]
    	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) ~[na:0.0]
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:0.0]
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:0.0]
    	at java.lang.Thread.run(Thread.java:923) ~[na:0.0]

**Comment by Alamo04** [comment]
Confirmed
With Medtronic pump it crashed while pump history is reading.
