### ISSUE TITLE
[Dev 2.8.2.5-dev] NSClient Full Sync Kills Nightscout?

### ISSUE THREAD

**Issue by parapenT1sta** [nightscout/AndroidAPS#717]
AndroidAPS 2.8.2.5-dev
Build: c0f911ad1-2021.10.06-13:16
Remote: https://github.com/nightscout/AndroidAPS.git
Flavor: fullrelease
Nightscout version: 14.2.3
Engineering mode enabled 

I've been using master since it was released and Nightscout always have been working perfectly fine even after the migration to mongoDB Atlas database but with 2.8.2.5-dev, my Nightscout site is crashed (Heroku), I only can it making working with NS Client paused and with Restart Dynos on Heroku. 

Also using xDrip but even with Cloud Upload disabled in the app, the same issue is happening.

Am I the only one facing this issue?
Any ideas how to fix it?

Master settings:
![Master_Settings](https://user-images.githubusercontent.com/608650/136458909-9adeb9f1-4836-41ec-865a-9a086a62b9b3.png)

Dev settings:
![Dev_Settings](https://user-images.githubusercontent.com/608650/136458978-75bf106f-ce59-4c0d-82b1-17cdb0d23bd8.png)

NSClient:
![NS_Client](https://user-images.githubusercontent.com/608650/136459048-d5d7baff-f1de-4459-be98-a1eb3693b26e.png)

**Comment by parapenT1sta** [comment]
> i'm running latest dev with latest NS master 14.2.2 without any problem Open heroku console to see what's going on ...

> i'm running latest dev with latest NS master 14.2.2 without any problem Open heroku console to see what's going on ...

```
2021-10-07T21:10:37.266768+00:00 app[web.1]: TypeError: Cannot read property '_id' of null
2021-10-07T21:10:37.266768+00:00 app[web.1]:     at hasId (/app/lib/server/cache.js:47:41)
2021-10-07T21:10:37.266769+00:00 app[web.1]:     at arrayFilter (/app/node_modules/lodash/lodash.js:582:11)
2021-10-07T21:10:37.266769+00:00 app[web.1]:     at Function.filter (/app/node_modules/lodash/lodash.js:9199:14)
2021-10-07T21:10:37.266770+00:00 app[web.1]:     at filterForAge (/app/lib/server/cache.js:46:16)
2021-10-07T21:10:37.266770+00:00 app[web.1]:     at mergeCacheArrays (/app/lib/server/cache.js:37:23)
2021-10-07T21:10:37.266771+00:00 app[web.1]:     at Stream.dataChanged (/app/lib/server/cache.js:83:30)
2021-10-07T21:10:37.266771+00:00 app[web.1]:     at Stream.emit (events.js:314:20)
2021-10-07T21:10:37.266771+00:00 app[web.1]:     at /app/lib/server/websocket.js:221:29
2021-10-07T21:10:37.266772+00:00 app[web.1]:     at executeCallback (/app/node_modules/mongodb/lib/operations/execute_operation.js:70:5)
2021-10-07T21:10:37.266772+00:00 app[web.1]:     at handleCallback (/app/node_modules/mongodb/lib/utils.js:102:55)
2021-10-07T21:10:37.169142+00:00 heroku[router]: at=info method=POST path="/socket.io/?EIO=3&transport=polling&sid=q4rXw9900N5tvFmzAAAA" host=********.herokuapp.com request_id=507a16ec-8462-43f2-b960-458279425ff6 fwd="188.37.1.218" dyno=web.1 connect=0ms service=2ms status=200 bytes=225 protocol=https
2021-10-07T21:10:37.395781+00:00 heroku[web.1]: Process exited with status 1
2021-10-07T21:10:37.257703+00:00 heroku[router]: at=info method=POST path="/socket.io/?EIO=3&transport=polling&t=NnSb_wi&sid=Tl4FnuAwRNHh97UGAAAB" host=********.herokuapp.com request_id=95e12395-0494-49c3-b531-c87b0e80eac0 fwd="188.37.1.218" dyno=web.1 connect=0ms service=28ms status=200 bytes=297 protocol=https
2021-10-07T21:10:37.257068+00:00 heroku[router]: at=info method=GET path="/socket.io/?EIO=3&transport=polling&sid=q4rXw9900N5tvFmzAAAA" host=*********.herokuapp.com request_id=317aa5aa-cafe-46ea-b103-31619c04a7b5 fwd="188.37.1.218" dyno=web.1 connect=0ms service=28ms status=200 bytes=415 protocol=https
2021-10-07T21:10:37.436729+00:00 heroku[web.1]: State changed from up to crashed
```
But if it is working for you and the Nightscout Dev version I am using is the same of Master 14.2.3. I'm closing the ticket.

**Comment by parapenT1sta** [comment]
I found the "problem". AndroidAPS was sending a "lot" of information and making my Nightscout crash, I cleared storage from AndroidAPS, and import my settings after the first app start and now the issue is solved.
I tried Clear Datadase from Maintenance mode but didn't help, only clearing storage and start a "clean" AndroidAPS installation helped.

**Comment by parapenT1sta** [comment]
Issue solved with AndroidAPS 3.0-beta1 version.

**Comment by cygrahampearson** [comment]
@parapenT1sta I am having this issue in 3.0-beta11. Have you run into this issue again or is it completely solved for you? I may try a fresh install of some other versions to see what is going on. Screenshot of lo

![Heroku](https://user-images.githubusercontent.com/73077567/147718300-7766c133-8388-449d-877d-ad00a7511978.PNG)
g

**Comment by parapenT1sta** [comment]
@cygrahampearson What Nightscout version do you have? Does your NS work after Restart Dynos?

Which number do you get on queue in NS Client after pressing Full Sync?

**Comment by Katekatekatie** [comment]
@parapenT1sta Thanks for getting back to me. I'm truly perplex by the situation. 

I've tried Version 3 beta 11 and 2.8 on three devices (unihertz atom, S9 and G7). They are all crashing nightscout.

I decided to rebuild nightscout from scratch with the latest version. I even used brand new mongo, heroku and github accounts. It is crashing all versions of AAPS.

I've even paid for a few T1pal accounts and they are all crashing now.

It works momentarily if I rebuild and restart dynos but crashes shortly after. 

The error in nightscout is ERROR io.socket.engineio.client.EngineIOException: xhr poll error

Any ideas? 

I've been running nightscout for almost two years with Loop without ever having any issues.

**Comment by Katekatekatie** [comment]
@parapenT1sta queue number is 341

**Comment by parapenT1sta** [comment]
@Katekatekatie At the time when I was troubleshooting, I did all kind of tests. I remember I had made a fresh AndroidAPS  installation, just importing the settings, I didn't create a new MongoDB but I cleared all databases to 0 days.

In MongDB I even tried to change Node.js version to 3.7 that at the time it appeared to fix the issue but I would come back with the same issue after many tests.You can try to change it to see the result, select Project, then on Cluster > Connect > Connect your application > Change from 4.0 or later to 3.7 or later.

**Comment by CharlotteNightscout** [comment]
HI @parapenT1sta i think i have the same problem... my queue in NS client is about 311,764 and my Nightscout and my closed loop only works when the NSclient is paused. Also my smartphone runs out of battery really quickly since i tried a full synchronisation. I am currently using Andorid APS 3.1.0.3. The restart of the dynos didn't change anything. Do i delete and install Android APs again or what did you mean with by "clear storage" and "clean installation"?

**Comment by parapenT1sta** [comment]
> HI @parapenT1sta i think i have the same problem... my queue in NS client is about 311,764 and my Nightscout and my closed loop only works when the NSclient is paused. Also my smartphone runs out of battery really quickly since i tried a full synchronisation. I am currently using Andorid APS 3.1.0.3. The restart of the dynos didn't change anything. Do i delete and install Android APs again or what did you mean with by "clear storage" and "clean installation"?

My Nightscout is now working properly with the latest NS and AAPS version.
I also set a token for full admin control. No issues so far.
