### ISSUE TITLE
OH

### ISSUE THREAD

**Issue by MilosKozak** [nightscout/AndroidAPS#974]
00:34:16.150 [DefaultDispatcher-worker-1] I/OHUPLOADER: [OpenHumansWorker.doWork():28]: Starting upload
00:34:16.458 [DefaultDispatcher-worker-1] E/OHUPLOADER: [OpenHumansWorker.doWork():34]: OH Uploader failed
java.lang.UnsupportedOperationException: Tried to obtain display from a Context not associated with  one. Only visual Contexts (such as Activity or one created with Context#createWindowContext) or ones created with Context#createDisplayContext are associated with displays. Other types of Contexts are typically related to background entities and may return an arbitrary display.
	at android.app.ContextImpl.getDisplay(ContextImpl.java:2602) ~[na:0.0]
	at android.content.ContextWrapper.getDisplay(ContextWrapper.java:1022) ~[na:0.0]
	at info.nightscout.androidaps.plugin.general.openhumans.OpenHumansUploader.uploadDataPaged(OpenHumansUploader.kt:237) ~[na:0.0]
	at info.nightscout.androidaps.plugin.general.openhumans.OpenHumansUploader.access$uploadDataPaged(OpenHumansUploader.kt:47) ~[na:0.0]
	at info.nightscout.androidaps.plugin.general.openhumans.OpenHumansUploader$uploadDataPaged$1.invokeSuspend(Unknown Source:19) ~[na:0.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[na:0.0]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[na:0.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[na:0.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) ~[na:0.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[na:0.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[na:0.0]

**Comment by MilosKozak** [comment]
fixed by https://github.com/nightscout/AndroidAPS/commit/60f5115ce63d91ee2330dfc0dac0eb6fd301b538
